# from flask import Flask, request#, jsonify, make_response, render_template
# # from flask_cors import CORS
# # from jbs import ir
# # from collections import Counter
# # from flask_mail import Mail
# # from flask_mail import Message
# # import pdfkit
#
# # configuration
# #DEBUG = True
#
# # instantiate the app
# app = Flask(__name__)
# app.config.from_object(__name__)
#
# # config flask mail with gmail, see https://stackoverflow.com/questions/37058567/configure-flask-mail-to-use-gmail
# app.config['MAIL_SERVER'] = 'smtp.gmail.com'
# app.config['MAIL_PORT'] = 465
# app.config['MAIL_USERNAME'] = 'iplaces74@gmail.com'
# # generated by google for this specific app
# app.config['MAIL_PASSWORD'] = 'ftvzrsdogdzwsgdk'
# app.config['MAIL_USE_TLS'] = False
# app.config['MAIL_USE_SSL'] = True
# mail = Mail(app)
#
# # enable CORS
# CORS(app, resources={r'/*': {'origins': '*'}})
# # CORS(app)
#
from flask import Flask, request
import json
# instantiate the app
from search import search

app = Flask(__name__)

@app.route("/wiki_by_place_il")
def RUN_SEARCH():
    params = []
    params.append(request.args.get('radius', type=str))
    params.append(request.args.get('lat', type=str))
    params.append(request.args.get('lon', type=str))
    return json.dumps(search(params), ensure_ascii=False)
    #return ''.join(str(dict)+', ' for dict in search(params))


if __name__ == "__main__":
    app.run()

""" HTML  request would be
http://127.0.0.1:5000/wiki_by_place_il?radius=xxx&lat=xxx&lon=xxx
example:
http://127.0.0.1:5000/wiki_by_place_il?radius=1km&lat=32.7775&lon=35.02166667
"""